CREATE DATABASE VINTELO;

USE VINTELO;

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    CELULAR_USUARIO CHAR(11) UNIQUE NOT NULL,
    EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    BAIRRO_USUARIO VARCHAR(30) NOT NULL,
    CIDADE_USUARIO VARCHAR(30) NOT NULL,
    UF_USUARIO CHAR(2) NOT NULL,
    CEP_USUARIO CHAR(8) NOT NULL,
    SENHA_USUARIO VARCHAR(255) NOT NULL
    );
    
CREATE TABLE CLIENTES (
	ID_USUARIO INT PRIMARY KEY,
    DATA_NASC DATE NOT NULL,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE BRECHOS (
    ID_USUARIO INT PRIMARY KEY,
    CNPJ_BRECHO CHAR(14) UNIQUE NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) UNIQUE NOT NULL,
    NOME_FANTASIA VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE ADMINISTRADORES (
    ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    CPF_ADM CHAR(11) NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );

CREATE TABLE PERFIS (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    SEGUIDORES INT NOT NULL,
    A_VENDA BOOLEAN NOT NULL,
    VENDIDAS INT NOT NULL,
    DESC_PERFIL VARCHAR(250) NOT NULL,
    IMG BLOB,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE PRODUTOS (
    ID_PROD INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    NOME_PROD VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    TAMANHO ENUM('XPP', 'PP', 'P', 'M', 'G', 'GG', 'XXG', 'U'),
    COR VARCHAR(30) NOT NULL,
	CONDICAO ENUM('novo', 'usado', 'semi-novo') NOT NULL,
    OUTROS TEXT,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE IMG_PRODUTOS (
ID_IMG INT PRIMARY KEY AUTO_INCREMENT,
ID_PROD INT NOT NULL,
URL_IMG VARCHAR(255) NOT NULL,
FOREIGN KEY (id_prod) REFERENCES PRODUTOS(id_prod)
);

CREATE TABLE CATEGORIAS_PRODUTOS (
ID_CATEGORIA_PROD INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA_PROD VARCHAR(100) NOT NULL
);

CREATE TABLE CARTOES (
ID_CARTAO INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO INT NOT NULL,
NOME_TITULAR VARCHAR(100) NOT NULL,
VALIDADE DATE NOT NULL,
CVV CHAR(3) NOT NULL,
FOREIGN KEY (id_usuario) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PEDIDOS (
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ID_PROD INT NOT NULL,
ID_USUARIO INT NOT NULL,
DT_PEDIDO DATETIME NOT NULL,
STATUS_PEDIDO ENUM('Pendente', 'Concluído', 'Cancelado', 'Enviado') NOT NULL,
VALOR_TOTAL DECIMAL(10,2) NOT NULL,
ID_CARTAO INT,
FOREIGN KEY (id_prod) REFERENCES PRODUTOS(id_prod),
FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario),
FOREIGN KEY (id_cartao) REFERENCES CARTOES(id_cartao)
);

CREATE TABLE AVALIACOES_BRECHOS (
ID_AVALIACAO_BRECHO INT PRIMARY KEY AUTO_INCREMENT,
NOTA INT NOT NULL,
HORA TIME NOT NULL,
COMENTARIO VARCHAR (500),
ID_USUARIO INT NOT NULL,
DT_AVALIACAO DATE NOT NULL
);

CREATE TABLE ARTIGOS_BLOG (
ID_ARTIGO INT AUTO_INCREMENT PRIMARY KEY,
ID_ADM INT NOT NULL,
TITULO VARCHAR (255) NOT NULL,
CONTEUDO TEXT NOT NULL,
DT_PUBLICACAO DATE NOT NULL
);

CREATE TABLE CATEGORIAS_BLOG (
ID_CATEGORIA_BLOG INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA_BLOG VARCHAR(100) NOT NULL
);









    
    
    
    
    